name: Run on Project

on:
    push:
        branches:
            - main
    pull_request: null

jobs:
    run_on_project:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['8.2']

        steps:
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   run: composer require rector/argtyper --ansi

            # clone laravel project with dependencies
            -   run: git clone https://github.com/laravel/framework.git --depth=1
            -   run: composer install --working-dir framework --ansi

            # on whole project, to be able to load vendor/autoload.php
            -   run: vendor/bin/argtyper add-types framework --ansi
